//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDSWI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.ListaVenta = new HashSet<ListaVenta>();
        }
    
        public int IdProducto { get; set; }
        public string NombrePro { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string Foto { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaVenta> ListaVenta { get; set; }
    }
}
